### ISSUE TITLE
Improving README file 

### ISSUE THREAD

**Issue by huamanraj** [huamanraj/PathPal#1]
crafting a readme file about the project 

the information to include with some rephrasing are 

AI-Based Counselling Platform(Chat-Bot):
Developing an AI-powered counselling platform that offers personalised career guidance based on students interests, skills, and aptitudes. 
The AI will be trained on a vast dataset of career information, job market trends, and educational paths.
Implementing AI algorithms to analyse the aptitude test results and provide personalised career suggestions. By using machine learning models to match the student's profile with various career options.
Providing detailed information on recommended career paths, including educational requirements, job prospects, salary ranges, and job descriptions.

The bot administers aptitude tests in various subjects and areas, such as mathematics, science, humanities, and arts. It then analyzes the test results to identify the student's strengths and areas for improvement.

Based on the initial assessment and aptitude test results, the bot provides personalized career recommendations. It suggests potential career paths that align with the student's interests and strengths.

The bot assists students in choosing the right courses and educational pathways to pursue their chosen careers.

The bot uses natural language processing to make the conversation feel engaging and intuitive.

The bot can provide links to educational resources, online courses, and career-related articles to help students further their knowledge and skills.

and must link contributed profile template

**Comment by suraj-markup** [comment]
I want to contribute to this issue. can you please assign this to me?

**Comment by huamanraj** [comment]
> I want to contribute to this issue. can you please assign this to me?
> 

Sure! Work on it

**Comment by huamanraj** [comment]
> I want to contribute to this issue. can you please assign this to me?

whats the status ?

**Comment by suraj-markup** [comment]
I'm working on it. I will commit today.

**Comment by huamanraj** [comment]
> I'm working on it. I will commit today.

?
