### ISSUE TITLE
Creating A separate script file!! 

### ISSUE THREAD

**Issue by huamanraj** [huamanraj/PathPal#4]
create a working separate js file!!

**Comment by adv8j** [comment]
I am interested in working on this issue. Can you elaborate more on what exactly has to be done and assign it to me?

**Comment by huamanraj** [comment]
> I am interested in working on this issue. Can you elaborate more on what exactly has to be done and assign it to me?

There is js written in the html file you have to make a separate file for js. 
Would you be able to?

**Comment by Fahass** [comment]
I'd like to work on this issue.

**Comment by adv8j** [comment]
> > I am interested in working on this issue. Can you elaborate more on what exactly has to be done and assign it to me?
> 
> There is js written in the html file you have to make a separate file for js. Would you be able to?

Oh okay. I thought there's some js required to be coded. You may assign it to @Fahass for this
